apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-pvc
  namespace: default
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: glpi-pv
  storageClassName: local-storage
  volumeMode: Filesystem
