apiVersion: v1
kind: PersistentVolume
metadata:
  name: glpi-pv
status:
  phase: Bound
spec:
  capacity:
    storage: 5Gi
  local:
    path: /data/glpi
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: glpi-pvc
    uid: 93d19e87-6b6c-47a1-87f0-7f3c063d87e2
    apiVersion: v1
    resourceVersion: '103137'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mjvm
